### ISSUE TITLE
case_sensitive=True gives unexpected results

### ISSUE THREAD

**Issue by nschloe** [barrust/pyspellchecker#122]
In a case-sensitive dictionary, I would expect `'FBI'` to be known and `'fbi'` to be unknown. However, both cases give me `'fbi'` as known:
```python
from spellchecker import SpellChecker

spell = SpellChecker(case_sensitive=True)

print(spell.known(["FBI"]))
print(spell.known(["fbi"]))
```
```python
{'fbi'}
{'fbi'}
```

**Comment by akhmerov** [comment]
That's because the language is set (`en` by default), and `case_sensitive` is ignored if language is set.

**Comment by nschloe** [comment]
Thanks for the reply! Is there way to get
```
{'FBI'}
{}
```
from the above code at all? (If `language=None`, both seem to be ignored.)

**Comment by barrust** [comment]
That is likely because you didn't add a dictionary. What dictionary did you add? 

Can you try something like this? This should work, I am not at a location to run it myself to verify no typos!

```python
from spellchecker import SpellChecker

spell = SpellChecker(language=None, case_sensitive=True) 
spell.word_frequency.add("FBI") 

print("FBI" in spell)
print("fbi" in spell)
```

**Comment by nschloe** [comment]
Ah wait, when using `language=None`, it actually only spellchecks words that I put in manually? That's not good enough for me. Is there no way to use a case-sensitive English dictionary?

**Comment by barrust** [comment]
To use a case_sensitive dictinoary, you will need to build it yourself as the default dictionaries are case-insensitive. There are lots of ways to build dictionaries, and they are not manually. I only used that to ensure that there wasn't a bug. You can find the different ways to build a custom dictionary in the [documentation on building a new dictionary](https://pyspellchecker.readthedocs.io/en/latest/quickstart.html#how-to-build-a-new-dictionary) or in the [GitHub Discussion #90](https://github.com/barrust/pyspellchecker/discussions/90).

Either way, there are reasons why the default dictionaries are not capitalized: 

- Reduce the number of characters to calculate all the differences
- Reduces the number of words to check (`The` vs. `the`) since the same word may be capitalized, say due to being the first word in the sentence. 
- The library does not take into account the type of word (entity, verb, adverb, etc) and thus cannot determine if the word being checked ***should*** be capitalized or not. 

Just some thoughts on it; good luck!

**Comment by nschloe** [comment]
Thanks for the info!
