### ISSUE TITLE
Is it possible to add other languages dictionaries?

### ISSUE THREAD

**Issue by marchezinixd** [barrust/pyspellchecker#22]
Hello,

I'm trying to use this library to fix typos done when adding additional information about a problem, but it's no restricted to english and spanish, we would like portuguese etc. Is there a way for me to download a dict and add it to the library?

**Comment by barrust** [comment]
You can load a new dictionary in, but it is actually more of a word frequency. So instead of it being a list of words (which you can also use by using the `load_text` or `load_text_file`  functions) it would need to be in JSON format with the key the term and an int as the key or frequency. 

A unicode error means that you are likely on python 2.7. Can you confirm which python version you are on?

**Comment by barrust** [comment]
Also, I am happy to support other dictionaries; PRs are appreciated!

**Comment by marchezinixd** [comment]
I think i can close this, it's the same problem in https://github.com/barrust/pyspellchecker/issues/21

**Comment by barrust** [comment]
Sounds good. I can build a Portuguese dictionary using the files from [this site](https://github.com/hermitdave/FrequencyWords/tree/master/content/2016/pt) if that is what you are looking for. I can make it a supported language at that point. Let me know in a new ticket requesting a language!
