### ISSUE TITLE
Memory Issue for long spellings errors/strings

### ISSUE THREAD

**Issue by khatrimann** [barrust/pyspellchecker#57]
For testing purposes I have given a word of length 20 and 100, in both the cases my server is giving me ```unable to allocate memory``` and my local machine, which is running on 8GB RAM,  hangs.

**Comment by barrust** [comment]
That sounds about right. The system has to build out every permutation of possible misspelling - insertions, deletions, transpositions, and replacements. It does this, then checks all the values for a valid value. If one is not found and edit distance is 2 (the default), then it does it again for each possible permutation. The longer the word provided, the longer it takes and the more memory it takes. It is not designed to work for random lengths of strings but on reasonable word lengths. 

One solution, would be to have the library not check any word that is larger than the largest word length  since that is the largest possible that could be found and if it is larger, then it will never be found.
