### ISSUE TITLE
pyspellchecker module and indexer 

### ISSUE THREAD

**Issue by pctjsm** [barrust/pyspellchecker#73]
With version 0.5.5 it does not work as there seems to be a problem with the pyspellchecker module right now. 
The stable version at the moment is 0.5.4.

Spellchecker module still relies on the indexer library, which is no longer supported by python3, any update planned?
Thank you in advance.

![image](https://user-images.githubusercontent.com/69590597/91415350-d6a8de00-e845-11ea-85de-187f178707b0.png)

**Comment by barrust** [comment]
Actually, this is because you are using a different spellchecking program and not pyspellchecker. `pyspellchecker` does not use the indexer module though `spellchecker` does. I have had several people let me know that there is a problem due to the indexer package but each time they have installed spellchecker and not pyspellchecker. 
I hope this helps!

Note: I do not have a core file like is being shown here in the error!

**Comment by barrust** [comment]
You must have installed this package: [spellchecker](https://pypi.org/project/spellchecker/)

Perhaps you have both packages installed, but this has the same namespace of `spellchecker` so it would interfere with each other.

**Comment by pctjsm** [comment]
Hi, yes there is a conflict. I had both packages.
Thank you for clarifying!
